In [1]:
import sys; sys.path.append("..")
from data_processing.load_ticker import load_ticker

spy_df = load_ticker(
    base_dir = "../../parquet_minute", 
    time_col = "Date",
    symbol_col="Symbol",
    seed = 42, 
    symbol= "SPY",
    verbose=True
)

spy_df

[LOAD TICKER] Loaded SPY: 61 files -> shape (488041, 7)
[LOAD TICKER] Date range: 2020-08-21 13:30:00+00:00  to  2025-08-21 19:59:00+00:00

,Date,Symbol,Open,High,Low,Close,Volume
0,2020-08-21 13:30:00+00:00,SPY,337.920013,338.029999,337.839996,337.929993,530274
1,2020-08-21 13:31:00+00:00,SPY,337.920013,338.079987,337.920013,338.000000,280279
2,2020-08-21 13:32:00+00:00,SPY,338.019989,338.040009,337.875000,338.000000,180445
3,2020-08-21 13:33:00+00:00,SPY,338.010010,338.083405,337.910004,338.029999,303505
4,2020-08-21 13:34:00+00:00,SPY,338.019989,338.089996,337.940002,338.059998,132404
...,...,...,...,...,...,...,...
488036,2025-08-21 19:55:00+00:00,SPY,635.669983,635.889893,635.659973,635.850098,407279
488037,2025-08-21 19:56:00+00:00,SPY,635.854980,635.885010,635.669983,635.700012,194769
488038,2025-08-21 19:57:00+00:00,SPY,635.710022,635.775024,635.409973,635.409973,315516
488039,2025-08-21 19:58:00+00:00,SPY,635.414978,635.474976,635.145020,635.184998,375316
488040,2025-08-21 19:59:00+00:00,SPY,635.190002,635.719971,635.080017,635.580017,1476968

In [2]:
from data_processing.clean_data import clean_data

spy_clean_df = clean_data(
    df=spy_df,
    timestamp_col = "Date",
    symbol_col = "Symbol",
    drop_duplicate_rows = True,
    drop_duplicate_cols = True,
    drop_constant_columns = True,
    drop_constant_rows = True,
    replace_placeholders = True,
    placeholders=("Null", "null", "NULL", "NaN", "nan", "NAN", "None", "none", "NONE"),
    fill_missing = True,
    convert_numeric = True,
    sort_by = "timestamp",
    verbose = True,
)

[---CLEAN---] Starting Shape=(488041, 7)
[---CLEAN---] Preserving: Symbol and Date
[---CLEAN---] Step 1: Remove Duplicate Columns.
[---CLEAN---] ------- Original Column Count: 7, After: 7, Removed: 0 in 0.05122s
[---CLEAN---] Step 2: Remove Duplicate Rows.
[---CLEAN---] ------- Original Row Count: 488041, After: 488041, Removed: 0 in 0.09238s
[---CLEAN---] Step 3: Remove Constant Columns.
[---CLEAN---] ------- Original Column Count: 7, After: 7, Removed: 0 in 0.02880s
[---CLEAN---] Step 4: Remove Constant Rows.
[---CLEAN---] ------- Original Row Count: 488041, After: 488041, Removed: 0 in 0.12237s
[---CLEAN---] Step 5: Replacing Placeholder Values
[---CLEAN---] ------- Total Nulls After Replacement: 0 in 0.01611s
[---CLEAN---] Step 6: Sorting by Timestamp.
[---CLEAN---] ------- Sorted by timestamp in 0.01858s
[---CLEAN---] Step 7: Interpolating Missing and NaN Values.
[---CLEAN---] ------- Initial Nulls: 0, After Fill: 0, Filled: 0 in 0.036s
[---CLEAN---] Step 8: Converting Data to Numerical Values.
[---CLEAN---] ------- Conversion complete in 0.003s
[---CLEAN---] Cleaning complete in 0.375s. Final shape: (488041, 7)